### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by mkoa** [wtma/CharBERT#2]
Hi!
Thanks a lot for this repository. Your results are very impressive!

I'd like to try it out, but unfortunately the download links for the pretrained models are down (I get a loading message hanging forever). Is there something you can do about this maybe?

Thanks a lot again ☺

**Comment by mawentao277** [comment]
Hi, sorry for the delay!
We have uploaded the models to google drive and changed the links, you can try it again.
Thank you!

**Comment by mkoa** [comment]
Thank you very much @wtma!
We've been able to use your models and fine tune them on our usecases with quite good results :100:
