### ISSUE TITLE
Output Linear Projection is Commented Out

### ISSUE THREAD

**Issue by eiphy** [wtma/CharBERT#6]
Hi @wtma ,

I found that the output projections of heterogeneous interaction are commented out. Is this because the performance is better without the projection or just by accident?
https://github.com/wtma/CharBERT/blob/0ac763bf077fbc672cfe70c4aa40454857d93963/modeling/modeling_bert.py#L410-L413

It's also commented out in forward:
https://github.com/wtma/CharBERT/blob/0ac763bf077fbc672cfe70c4aa40454857d93963/modeling/modeling_bert.py#L450-L451

**Comment by mawentao277** [comment]
Hello @eiphy , sorry for the delay!
I think it is just by accident and it will not make much difference for the performance.

**Comment by eiphy** [comment]
Thanks for your kindly reply.

**Comment by eiphy** [comment]
Hi @wtma,

This brings me another problem. So do you really directly use the result after two feed forwaeds or just directly use the share representation (which seems to be the case in https://github.com/wtma/CharBERT/blob/0ac763bf077fbc672cfe70c4aa40454857d93963/modeling/modeling_bert.py#L446-L453).

Besides, the word and character representation are actually input into same bert layers twice and independently. Is this the case? :https://github.com/wtma/CharBERT/blob/0ac763bf077fbc672cfe70c4aa40454857d93963/modeling/modeling_bert.py#L438-L439

Thanks and looking forward to your reply.

**Comment by mawentao277** [comment]
Hello @eiphy ,
For the first question, we directly use the `share_hidden` without the two feed forwards in the latter residual operation;
For the second, as we need to share the parameters of transformer layers, so the word and character representation are indeed input into same layers twice and independently.
Thank you!

**Comment by eiphy** [comment]
Thanks for explanation. I'll close this issue.
